### ISSUE TITLE
availability of Visium spatial transcriptomic data

### ISSUE THREAD

**Issue by LuyiTian** [massonix/HCATonsilData#8]
Hi, could you please inform where can I find the Visium data in your paper? Thanks~

**Comment by massonix** [comment]
Hi LuyiTian,

We are working on a pipeline to make our spatial data available as a SpatialExperiment through HCATonsilData. In the meantime, I could provide you with the Seurat object saved as a .rds file. Kindly, could you please give me your email so I can send it to you?

Thanks and best

Ramon

**Comment by LuyiTian** [comment]
Hi Ramon, I have emailed you with my broad email. Thank you for your help.

**Comment by massonix** [comment]
Hi Luyi, I shared the Seurat object with you via email.

For other users wanting the data, please email me and I will share it without problems. Currently working on other stuff, but I will try to get it both at Zenodo and HCATonsilData ASAP

**Comment by LuyiTian** [comment]
I got the data and thank you for quick reply!

**Comment by denvercal1234GitHub** [comment]
Hi @massonix - I had email you from quang.nguyen@ndm.ox.ac.uk email to request the spatial data. Thank you again very much for your help!

**Comment by massonix** [comment]
Hi Quang!

Thank you very much for your kind patience, these last days have been pretty hectic with the preparation of the thesis defense. I will now send you an email with the Visium data, and later I will address all your emails and requests one by one.

Warm regards,

Ramon

**Comment by massonix** [comment]
Sent
